#if UNITY_EDITOR
using System;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

/// <summary>
/// Import policy and automatic scene handoff for assets generated by AI Assistant.
/// Blender exports unique reusable models under Assets/AI_Generated/Models and
/// writes an .aiscene.json manifest under Assets/AI_Generated/Scenes. Unity
/// imports the models, then this postprocessor idempotently assembles the requested
/// instances into the currently open scene.
/// </summary>
public sealed class AIGeneratedAssetPostprocessor : AssetPostprocessor
{
    private const string GeneratedRoot = "Assets/AI_Generated/";
    private const string SceneManifestExtension = ".aiscene.json";

    private void OnPreprocessModel()
    {
        if (!assetPath.StartsWith(GeneratedRoot, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        ModelImporter importer = assetImporter as ModelImporter;
        if (importer == null)
        {
            return;
        }

        importer.globalScale = 1f;
        importer.importCameras = false;
        importer.importLights = false;
        importer.importBlendShapes = true;
        importer.isReadable = false;
        importer.meshCompression = ModelImporterMeshCompression.Off;
        importer.optimizeMeshPolygons = true;
        importer.optimizeMeshVertices = true;
    }

    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths
    )
    {
        foreach (string path in importedAssets)
        {
            if (!path.StartsWith(GeneratedRoot, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (path.EndsWith(SceneManifestExtension, StringComparison.OrdinalIgnoreCase))
            {
                string capturedPath = path;
                EditorApplication.delayCall += () => BuildSceneFromManifest(capturedPath);
                continue;
            }

            if (path.EndsWith(".aiasset.json", StringComparison.OrdinalIgnoreCase))
            {
                Debug.Log("[AI Asset Pipeline] Manifest imported: " + path);
                continue;
            }

            if (path.EndsWith(".topology.json", StringComparison.OrdinalIgnoreCase))
            {
                Debug.Log("[AI Asset Pipeline] Topology report imported: " + path);
                continue;
            }

            string extension = Path.GetExtension(path).ToLowerInvariant();
            if (extension == ".fbx" || extension == ".glb" || extension == ".gltf")
            {
                Debug.Log("[AI Asset Pipeline] Generated model ready: " + path);
            }
        }
    }

    private static void BuildSceneFromManifest(string manifestAssetPath)
    {
        try
        {
            string projectRoot = Directory.GetParent(Application.dataPath)?.FullName;
            if (string.IsNullOrWhiteSpace(projectRoot))
            {
                Debug.LogError("[AI Asset Pipeline] Could not resolve project root for scene manifest.");
                return;
            }

            string absoluteManifest = Path.Combine(
                projectRoot,
                manifestAssetPath.Replace('/', Path.DirectorySeparatorChar)
            );

            if (!File.Exists(absoluteManifest))
            {
                Debug.LogWarning("[AI Asset Pipeline] Scene manifest disappeared before assembly: " + manifestAssetPath);
                return;
            }

            GeneratedSceneManifest manifest = JsonUtility.FromJson<GeneratedSceneManifest>(
                File.ReadAllText(absoluteManifest)
            );

            if (manifest == null || manifest.instances == null || manifest.instances.Length == 0)
            {
                Debug.LogWarning("[AI Asset Pipeline] Scene manifest contains no instances: " + manifestAssetPath);
                return;
            }

            string rootName = string.IsNullOrWhiteSpace(manifest.rootName)
                ? "AI_Generated_Scene"
                : manifest.rootName;

            GameObject existingRoot = FindSceneObject(rootName);
            if (existingRoot != null)
            {
                if (!manifest.replaceExisting)
                {
                    Debug.Log(
                        "[AI Asset Pipeline] Existing generated scene root retained: "
                        + rootName
                    );
                    return;
                }

                UnityEngine.Object.DestroyImmediate(existingRoot);
            }

            GameObject sceneRoot = new GameObject(rootName);
            int instantiated = 0;
            int missing = 0;

            foreach (GeneratedSceneInstance instance in manifest.instances)
            {
                if (instance == null || string.IsNullOrWhiteSpace(instance.assetPath))
                {
                    missing++;
                    continue;
                }

                AssetDatabase.ImportAsset(
                    instance.assetPath,
                    ImportAssetOptions.ForceSynchronousImport
                );

                GameObject model = AssetDatabase.LoadAssetAtPath<GameObject>(
                    instance.assetPath
                );

                if (model == null)
                {
                    Debug.LogWarning(
                        "[AI Asset Pipeline] Model not ready for scene assembly: "
                        + instance.assetPath
                    );
                    missing++;
                    continue;
                }

                GameObject created = PrefabUtility.InstantiatePrefab(model) as GameObject;
                if (created == null)
                {
                    created = UnityEngine.Object.Instantiate(model);
                }

                created.name = string.IsNullOrWhiteSpace(instance.name)
                    ? model.name
                    : instance.name;
                created.transform.SetParent(sceneRoot.transform, false);
                created.transform.localPosition = ReadVector(instance.position, Vector3.zero);
                created.transform.localEulerAngles = ReadVector(instance.rotation, Vector3.zero);
                created.transform.localScale = ReadVector(instance.scale, Vector3.one, true);
                instantiated++;
            }

            if (instantiated == 0)
            {
                UnityEngine.Object.DestroyImmediate(sceneRoot);
                Debug.LogError(
                    "[AI Asset Pipeline] Scene assembly failed: no generated model could be instantiated."
                );
                return;
            }

            Undo.RegisterCreatedObjectUndo(sceneRoot, "AI Generated Scene");
            Selection.activeGameObject = sceneRoot;
            EditorSceneManager.MarkSceneDirty(EditorSceneManager.GetActiveScene());
            EditorSceneManager.SaveOpenScenes();

            Debug.Log(
                "[AI Asset Pipeline] Scene assembled: "
                + rootName
                + " | instances=" + instantiated
                + " | missing=" + missing
                + " | manifest=" + manifestAssetPath
            );
        }
        catch (Exception ex)
        {
            Debug.LogError(
                "[AI Asset Pipeline] Scene manifest assembly failed: "
                + ex.GetType().Name
                + ": "
                + ex.Message
            );
        }
    }

    private static GameObject FindSceneObject(string name)
    {
        return Resources.FindObjectsOfTypeAll<GameObject>()
            .FirstOrDefault(candidate =>
                candidate != null
                && candidate.scene.IsValid()
                && candidate.scene.isLoaded
                && candidate.name.Equals(name, StringComparison.Ordinal)
            );
    }

    private static Vector3 ReadVector(
        float[] values,
        Vector3 fallback,
        bool protectZeroScale = false
    )
    {
        if (values == null || values.Length < 3)
        {
            return fallback;
        }

        Vector3 result = new Vector3(values[0], values[1], values[2]);
        if (protectZeroScale)
        {
            if (Mathf.Abs(result.x) < 0.0001f) result.x = 1f;
            if (Mathf.Abs(result.y) < 0.0001f) result.y = 1f;
            if (Mathf.Abs(result.z) < 0.0001f) result.z = 1f;
        }

        return result;
    }

    [MenuItem("AI Assistant/Generated Assets/Reveal Folder")]
    private static void RevealGeneratedFolder()
    {
        DirectoryInfo projectDirectory = Directory.GetParent(Application.dataPath);
        if (projectDirectory == null)
        {
            Debug.LogWarning("[AI Asset Pipeline] Could not resolve Unity project root.");
            return;
        }

        string absolute = Path.Combine(
            projectDirectory.FullName,
            "Assets",
            "AI_Generated"
        );
        Directory.CreateDirectory(absolute);
        EditorUtility.RevealInFinder(absolute);
    }

    [MenuItem("AI Assistant/Generated Assets/Reimport All")]
    private static void ReimportAll()
    {
        AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
        Debug.Log("[AI Asset Pipeline] Generated assets refreshed.");
    }

    [Serializable]
    private sealed class GeneratedSceneManifest
    {
        public int version;
        public string sceneName;
        public string rootName;
        public bool replaceExisting = true;
        public GeneratedSceneInstance[] instances;
    }

    [Serializable]
    private sealed class GeneratedSceneInstance
    {
        public string assetPath;
        public string name;
        public float[] position;
        public float[] rotation;
        public float[] scale;
    }
}
#endif
