#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;

/// <summary>
/// Import policy and automatic scene handoff for assets generated by AI Assistant.
/// Blender exports unique reusable models under Assets/AI_Generated/Models and
/// writes an .aiscene.json manifest under Assets/AI_Generated/Scenes. Unity
/// imports the models, then this postprocessor idempotently assembles the requested
/// instances into the currently open scene and performs a conservative spatial
/// sanity pass (grounding + duplicate overlap correction).
/// </summary>
public sealed class AIGeneratedAssetPostprocessor : AssetPostprocessor
{
    private const string GeneratedRoot = "Assets/AI_Generated/";
    private const string SceneManifestExtension = ".aiscene.json";

    private void OnPreprocessModel()
    {
        if (!assetPath.StartsWith(GeneratedRoot, StringComparison.OrdinalIgnoreCase))
        {
            return;
        }

        ModelImporter importer = assetImporter as ModelImporter;
        if (importer == null)
        {
            return;
        }

        importer.globalScale = 1f;
        importer.importCameras = false;
        importer.importLights = false;
        importer.importBlendShapes = true;
        importer.isReadable = false;
        importer.meshCompression = ModelImporterMeshCompression.Off;
        importer.optimizeMeshPolygons = true;
        importer.optimizeMeshVertices = true;
    }

    private static void OnPostprocessAllAssets(
        string[] importedAssets,
        string[] deletedAssets,
        string[] movedAssets,
        string[] movedFromAssetPaths
    )
    {
        foreach (string path in importedAssets)
        {
            if (!path.StartsWith(GeneratedRoot, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (path.EndsWith(SceneManifestExtension, StringComparison.OrdinalIgnoreCase))
            {
                string capturedPath = path;
                EditorApplication.delayCall += () => BuildSceneFromManifest(capturedPath);
                continue;
            }

            if (path.EndsWith(".aiasset.json", StringComparison.OrdinalIgnoreCase))
            {
                Debug.Log("[AI Asset Pipeline] Manifest imported: " + path);
                continue;
            }

            if (path.EndsWith(".topology.json", StringComparison.OrdinalIgnoreCase))
            {
                Debug.Log("[AI Asset Pipeline] Topology report imported: " + path);
                continue;
            }

            string extension = Path.GetExtension(path).ToLowerInvariant();
            if (extension == ".fbx" || extension == ".glb" || extension == ".gltf")
            {
                Debug.Log("[AI Asset Pipeline] Generated model ready: " + path);
            }
        }
    }

    private static void BuildSceneFromManifest(string manifestAssetPath)
    {
        try
        {
            string projectRoot = Directory.GetParent(Application.dataPath)?.FullName;
            if (string.IsNullOrWhiteSpace(projectRoot))
            {
                Debug.LogError("[AI Asset Pipeline] Could not resolve project root for scene manifest.");
                return;
            }

            string absoluteManifest = Path.Combine(
                projectRoot,
                manifestAssetPath.Replace('/', Path.DirectorySeparatorChar)
            );

            if (!File.Exists(absoluteManifest))
            {
                Debug.LogWarning("[AI Asset Pipeline] Scene manifest disappeared before assembly: " + manifestAssetPath);
                return;
            }

            GeneratedSceneManifest manifest = JsonUtility.FromJson<GeneratedSceneManifest>(
                File.ReadAllText(absoluteManifest)
            );

            if (manifest == null || manifest.instances == null || manifest.instances.Length == 0)
            {
                Debug.LogWarning("[AI Asset Pipeline] Scene manifest contains no instances: " + manifestAssetPath);
                return;
            }

            string rootName = string.IsNullOrWhiteSpace(manifest.rootName)
                ? "AI_Generated_Scene"
                : manifest.rootName;

            GameObject existingRoot = FindSceneObject(rootName);
            if (existingRoot != null)
            {
                if (!manifest.replaceExisting)
                {
                    Debug.Log("[AI Asset Pipeline] Existing generated scene root retained: " + rootName);
                    return;
                }

                UnityEngine.Object.DestroyImmediate(existingRoot);
            }

            GameObject sceneRoot = new GameObject(rootName);
            List<SpawnedInstance> spawned = new List<SpawnedInstance>();
            int instantiated = 0;
            int missing = 0;

            foreach (GeneratedSceneInstance instance in manifest.instances)
            {
                if (instance == null || string.IsNullOrWhiteSpace(instance.assetPath))
                {
                    missing++;
                    continue;
                }

                AssetDatabase.ImportAsset(
                    instance.assetPath,
                    ImportAssetOptions.ForceSynchronousImport
                );

                GameObject model = AssetDatabase.LoadAssetAtPath<GameObject>(instance.assetPath);
                if (model == null)
                {
                    Debug.LogWarning("[AI Asset Pipeline] Model not ready for scene assembly: " + instance.assetPath);
                    missing++;
                    continue;
                }

                GameObject created = PrefabUtility.InstantiatePrefab(model) as GameObject;
                if (created == null)
                {
                    created = UnityEngine.Object.Instantiate(model);
                }

                created.name = string.IsNullOrWhiteSpace(instance.name)
                    ? model.name
                    : instance.name;
                created.transform.SetParent(sceneRoot.transform, false);
                created.transform.localPosition = ReadVector(instance.position, Vector3.zero);
                created.transform.localEulerAngles = ReadVector(instance.rotation, Vector3.zero);
                created.transform.localScale = ReadVector(instance.scale, Vector3.one, true);

                spawned.Add(new SpawnedInstance
                {
                    GameObject = created,
                    AssetPath = instance.assetPath
                });
                instantiated++;
            }

            if (instantiated == 0)
            {
                UnityEngine.Object.DestroyImmediate(sceneRoot);
                Debug.LogError("[AI Asset Pipeline] Scene assembly failed: no generated model could be instantiated.");
                return;
            }

            float groundY = ResolveGroundY();
            int grounded = GroundInstances(spawned, groundY);
            int nudged = ResolveDuplicateOverlaps(spawned);

            Undo.RegisterCreatedObjectUndo(sceneRoot, "AI Generated Scene");
            Selection.activeGameObject = sceneRoot;
            EditorSceneManager.MarkSceneDirty(sceneRoot.scene);
            EditorSceneManager.SaveOpenScenes();

            Debug.Log(
                "[AI Asset Pipeline] Scene assembled: "
                + rootName
                + " | instances=" + instantiated
                + " | missing=" + missing
                + " | grounded=" + grounded
                + " | overlapFixes=" + nudged
                + " | manifest=" + manifestAssetPath
            );
        }
        catch (Exception ex)
        {
            Debug.LogError(
                "[AI Asset Pipeline] Scene manifest assembly failed: "
                + ex.GetType().Name
                + ": "
                + ex.Message
            );
        }
    }

    private static int GroundInstances(List<SpawnedInstance> spawned, float groundY)
    {
        int count = 0;
        foreach (SpawnedInstance item in spawned)
        {
            if (item?.GameObject == null)
            {
                continue;
            }

            if (!TryGetWorldBounds(item.GameObject, out Bounds bounds))
            {
                continue;
            }

            float delta = groundY - bounds.min.y;
            if (Mathf.Abs(delta) <= 0.01f)
            {
                continue;
            }

            Vector3 position = item.GameObject.transform.position;
            position.y += delta;
            item.GameObject.transform.position = position;
            count++;
        }
        return count;
    }

    private static int ResolveDuplicateOverlaps(List<SpawnedInstance> spawned)
    {
        int fixes = 0;
        foreach (IGrouping<string, SpawnedInstance> group in spawned
            .Where(x => x != null && x.GameObject != null && !string.IsNullOrWhiteSpace(x.AssetPath))
            .GroupBy(x => x.AssetPath, StringComparer.OrdinalIgnoreCase))
        {
            List<SpawnedInstance> items = group.ToList();
            if (items.Count < 2)
            {
                continue;
            }

            for (int i = 1; i < items.Count; i++)
            {
                SpawnedInstance current = items[i];
                if (!TryGetWorldBounds(current.GameObject, out Bounds currentBounds))
                {
                    continue;
                }

                int guard = 0;
                while (guard++ < 8)
                {
                    bool severeOverlap = false;
                    float requiredShift = 0f;

                    for (int j = 0; j < i; j++)
                    {
                        if (!TryGetWorldBounds(items[j].GameObject, out Bounds other))
                        {
                            continue;
                        }

                        if (!OverlapsSeverelyXZ(currentBounds, other))
                        {
                            continue;
                        }

                        severeOverlap = true;
                        requiredShift = Mathf.Max(
                            requiredShift,
                            (currentBounds.extents.x + other.extents.x) + 0.6f
                        );
                    }

                    if (!severeOverlap)
                    {
                        break;
                    }

                    Vector3 p = current.GameObject.transform.position;
                    p.x += Mathf.Max(0.75f, requiredShift);
                    current.GameObject.transform.position = p;
                    TryGetWorldBounds(current.GameObject, out currentBounds);
                    fixes++;
                }
            }
        }

        return fixes;
    }

    private static bool OverlapsSeverelyXZ(Bounds a, Bounds b)
    {
        float overlapX = Mathf.Min(a.max.x, b.max.x) - Mathf.Max(a.min.x, b.min.x);
        float overlapZ = Mathf.Min(a.max.z, b.max.z) - Mathf.Max(a.min.z, b.min.z);
        if (overlapX <= 0f || overlapZ <= 0f)
        {
            return false;
        }

        float minX = Mathf.Max(0.001f, Mathf.Min(a.size.x, b.size.x));
        float minZ = Mathf.Max(0.001f, Mathf.Min(a.size.z, b.size.z));
        return overlapX / minX > 0.65f && overlapZ / minZ > 0.65f;
    }

    private static float ResolveGroundY()
    {
        GameObject ground = FindSceneObject("Ground") ?? FindSceneObject("Terrain");
        if (ground == null)
        {
            return 0f;
        }

        Collider collider = ground.GetComponent<Collider>();
        if (collider != null)
        {
            return collider.bounds.max.y;
        }

        Renderer renderer = ground.GetComponent<Renderer>();
        if (renderer != null)
        {
            return renderer.bounds.max.y;
        }

        return ground.transform.position.y;
    }

    private static bool TryGetWorldBounds(GameObject root, out Bounds bounds)
    {
        Renderer[] renderers = root.GetComponentsInChildren<Renderer>(true);
        if (renderers.Length == 0)
        {
            bounds = default;
            return false;
        }

        bounds = renderers[0].bounds;
        for (int i = 1; i < renderers.Length; i++)
        {
            bounds.Encapsulate(renderers[i].bounds);
        }
        return true;
    }

    private static GameObject FindSceneObject(string name)
    {
        return Resources.FindObjectsOfTypeAll<GameObject>()
            .FirstOrDefault(candidate =>
                candidate != null
                && candidate.scene.IsValid()
                && candidate.scene.isLoaded
                && candidate.name.Equals(name, StringComparison.Ordinal)
            );
    }

    private static Vector3 ReadVector(float[] values, Vector3 fallback, bool protectZeroScale = false)
    {
        if (values == null || values.Length < 3)
        {
            return fallback;
        }

        Vector3 result = new Vector3(values[0], values[1], values[2]);
        if (protectZeroScale)
        {
            if (Mathf.Abs(result.x) < 0.0001f) result.x = 1f;
            if (Mathf.Abs(result.y) < 0.0001f) result.y = 1f;
            if (Mathf.Abs(result.z) < 0.0001f) result.z = 1f;
        }

        return result;
    }

    [MenuItem("AI Assistant/Generated Assets/Reveal Folder")]
    private static void RevealGeneratedFolder()
    {
        DirectoryInfo projectDirectory = Directory.GetParent(Application.dataPath);
        if (projectDirectory == null)
        {
            Debug.LogWarning("[AI Asset Pipeline] Could not resolve Unity project root.");
            return;
        }

        string absolute = Path.Combine(projectDirectory.FullName, "Assets", "AI_Generated");
        Directory.CreateDirectory(absolute);
        EditorUtility.RevealInFinder(absolute);
    }

    [MenuItem("AI Assistant/Generated Assets/Reimport All")]
    private static void ReimportAll()
    {
        AssetDatabase.Refresh(ImportAssetOptions.ForceSynchronousImport);
        Debug.Log("[AI Asset Pipeline] Generated assets refreshed.");
    }

    [Serializable]
    private sealed class GeneratedSceneManifest
    {
        public int version;
        public string sceneName;
        public string rootName;
        public bool replaceExisting = true;
        public GeneratedSceneInstance[] instances;
    }

    [Serializable]
    private sealed class GeneratedSceneInstance
    {
        public string assetPath;
        public string name;
        public float[] position;
        public float[] rotation;
        public float[] scale;
    }

    private sealed class SpawnedInstance
    {
        public GameObject GameObject;
        public string AssetPath;
    }
}
#endif
